{% set version = "0.1.0" %}

package:
  name: smhm
  version: {{ version }}

source:
  git_url: https://github.com/sondale-git/SMHM.git
  git_rev: master 
#  git_rev: v0.1.0 
# line up would refer to tag v0.1.0, if master then if refers to branch master

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
    - pandas
    - requests
    - numpy
  host:
    - python
    - pip
    - setuptools
  test:
    imports:
    - SMHM
    - SMHM.HistoricalMunicipalMapper
    - SMHM.HistoricalMunicipalMapper.MunicipalityMapper

about:
  home: https://github.com/sondale-git/SMHM
  license: MIT
  summary: 'Swiss Municipal Historical Mapper'
  dev_url: https://github.com/sondale-git/SMHM.git
  doc_source_url: https://github.com/sondale-git/SMHM/blob/master/README.rst
