{% set version = "0.1.2" %}

package:
  name: smhm
  version: {{ version }}

source:
  git_url: https://github.com/sondalex/SMHM.git
#  git_rev: master
   git_rev: v0.1.2
# line up would refer to tag v0.1.2, if master then if refers to branch master

requirements:
  # build:
  # seems that this section is for compiling code.
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pandas
    - requests
    - numpy

  test:
    imports:
    - SMHM
    - SMHM.HistoricalMunicipalMapper
    - SMHM.HistoricalMunicipalMapper.MunicipalityMapper

about:
  home: https://github.com/sondalex/SMHM
  license: MIT
  summary: 'Swiss Municipal Historical Mapper'
  dev_url: https://github.com/sondalex/SMHM.git
  doc_source_url: https://github.com/sondalex/SMHM/blob/master/README.md
