{% set version = "0.1.0" %}

package:
  name: smhm
  version: {{ version }}

source:
  git_url: https://github.com/sondale-git/SMHM.git

build:
  noarch: python
  number: 0

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
  test:
    imports:
    - 

about:
  home: https://github.com/sondale-git/SMHM
  license: MIT
  summary: 'Swiss Municipal Historical Mapper'
  dev_url: https://github.com/sondale-git/SMHM.git
  doc_source_url: https://github.com/sondale-git/SMHM/blob/master/README.rst
